@api = http://localhost:3000/employees

GET {{api}}

###
POST {{api}}
Content-Type: application/json

{
    "Name": "Chen Sikunda",
    "Email": "chen1212@gmail.com",
    "Mobile": "0526648131",
    "Department": "Creative"
}


###
DELETE {{api}}/5

###
GET {{api}}/count

###
PUT {{api}}/3
Content-Type: application/json

{
    "Name": "Mila Sikunda",
    "Email": "milaaa@gmail.com",
    "Mobile": "0526867731",
    "Department": "Product",
    "HireDate": "2020-12-03"
}

